### ISSUE TITLE
Keyboard Shortcuts (cross platform)

### ISSUE THREAD

**Issue by bakercp** [olab-io/ofSketch#1]
Currently run command works on OSX, but wasn't working on firefox on Ubuntu64.

I believe ACE has a method for shortcuts based on platform.

Alternatively this may be a firefox-related bug.

Anyway, should test.

**Comment by brannondorsey** [comment]
Ace does have a method that is cross platform, but unfortunately the key bindings seem to be linked to the editor element alone, not the document. This means that key presses can only be tracked when the editor is in focus. I am currently employing a method similar to [this](http://stackoverflow.com/a/20009705/1833823) for both the run (cmd-r) and the save (cmd-s) shortcuts. I have also played around with [jquery.hotkeys.js](https://github.com/tzuryby/jquery.hotkeys) with mixed results (seems like the opposite problem occurs to the ACE bindings. Whenever the editor is selected the hotkey bindings are overriden by ACE.). Finally, browsers also seem to be a bit finicky about what default keybindings you can change: http://stackoverflow.com/questions/7295508/javascript-capture-browser-shortcuts-ctrlt-n-w?answertab=votes#tab-top

**Comment by bakercp** [comment]
Moving this to v0.2.0 milestone.  It's not essential

**Comment by brannondorsey** [comment]
I believe that I fixed this issue, however I do not currently have a cross-platform setup with which to test it. Can someone confirm that the basic keybindings now work cross-platform (with code at the develop branch)?

**Comment by brannondorsey** [comment]
Just tested on Ubuntu64 and we are all set. Closing this for now.
