### ISSUE TITLE
ofSketch must be installed on a path without spaces.

### ISSUE THREAD

**Issue by mrado1** [olab-io/ofSketch#106]
When I try to open examples sketches, I get the following error:

Makefile:13: Technologies/_Projects/ofSketch_v0.3.2_osx_release/data/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk: No such file or directory
make: **\* No rule to make target `Technologies/_Projects/ofSketch_v0.3.2_osx_release/data/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk'.  Stop.

Should I download a different version than v.0.3.2?

**Comment by brannondorsey** [comment]
No v0.3.2 should work correctly. When you open ofSketch do you see a modal pop up informing you that you have missing dependencies?

**Comment by mrado1** [comment]
No, I don't see anything pop up. I don't have to install openFrameworks, do
I?

**Comment by brannondorsey** [comment]
No you shouldn't have to download openFrameworks, as there is a distribution located inside of the `ofSketch_v0.3.2_osx_release/data` folder already. You may wan't to check and make sure if that folder is present and in order.

Is your ofSketch app still in the same directory as the `data/` folder that it came with?

**Comment by bakercp** [comment]
We fixed this. The issue was spaces in the path.
 Make files fail with that. We need to document this and add an issue.

**Comment by brannondorsey** [comment]
Ah, spaces in which path?

**Comment by bakercp** [comment]
Path to the app itself.

**Comment by brannondorsey** [comment]
The Download section in the README.md now mentions this requirement.
