### ISSUE TITLE
Front End Input Validation

### ISSUE THREAD

**Issue by bakercp** [olab-io/ofSketch#11]
- [ ] Project Names (new names and renaming)
- [ ] ?

**Comment by brannondorsey** [comment]
Anything with an input text field.

**Comment by brannondorsey** [comment]
Illegal characters block input and trigger a tooltip popup.

**Comment by brannondorsey** [comment]
There is currently no validator for checking if project or class name already exists.

**Comment by brannondorsey** [comment]
- Validator now checks if project or class name already exists.
- Improved validation error alerts
- Validated input fields no longer block certain illegal keypresses (internationalization)
