### ISSUE TITLE
File Upload

### ISSUE THREAD

**Issue by bakercp** [olab-io/ofSketch#16]
- ofxHTTP already supports file upload.
- We need file management for users to upload files to their data folder.

**Comment by brannondorsey** [comment]
Im having trouble figuring out how to add a file upload route with ofxHTTP. I remember you had it working with a very old version of ofSketch but I haven't been able to find the server code to handle a request to the `/upload` route. I also didn't see any ofxHTTP examples of this in action. Could you post some example code to get me pointed in the right direction?

**Comment by bakercp** [comment]
An upload (aka "post") route is already configured in our server at the root node "/".  It is accessed much like this:

https://github.com/bakercp/ofxHTTP/tree/master/example_basic_post_server

You can access its settings in the `ofx::HTTP::BasicJSONRPCServerSettings` object.

You should find callbacks for post data / progress, etc events in the App.h/App.cpp.

**Comment by bakercp** [comment]
Removed the requirement for file management for the time being.  This issue is closed.
