### ISSUE TITLE
Basic System for ofxAddon Inclusion

### ISSUE THREAD

**Issue by bakercp** [olab-io/ofSketch#20]
- Point to addons directory.
- Check-box style interface to include addons.

**Comment by bakercp** [comment]
We currently have the server side capabilities. 

Todo:
- [x] Client side checkboxes.
- [ ] Header inclusion.
- [x] `addons.make` generation.

**Comment by brannondorsey** [comment]
I am going to make this a top priority after v0.3.0. Until we think a little bit more about the official ofxAddon inclusion process for ofSketch discussed here https://github.com/olab-io/ofSketch/issues/87, I am not going to do any automated header inclusion. Client side checkboxes will simply write to `addons.make`. Perhaps I will also include a URL bar to copy github repos into the addons folder with ofxGit for now. That should give us a barebones addon system that we can evaluate once the community has played with it for a while. @bakercp, what do you think?

**Comment by brannondorsey** [comment]
Supported as of v0.3.0 :)
