### ISSUE TITLE
Parse Compiler Ouput

### ISSUE THREAD

**Issue by bakercp** [olab-io/ofSketch#21]
Provide in-line compiler error help via ACE

**Comment by brannondorsey** [comment]
Seems to be working, although not heavily tested.

**Comment by bakercp** [comment]
Testing now!

**Comment by brannondorsey** [comment]
Some indication also needs to be made as to what tabs have errors. Right now unsaved tabs appear red, but I think I am going to change that so that tabs with errors are red and unsaved tabs are another color.

**Comment by bakercp** [comment]
Parsing works really well in my quick tests on OSX and Linux!  It even parses warnings, which is super cool.  Excellent work! 

Perhaps the tags could have "badges" rather than just color changes?

![openlab](https://cloud.githubusercontent.com/assets/300484/3802128/5769c882-1c0b-11e4-8ed5-e70b2ad2a14d.png)

**Comment by brannondorsey** [comment]
Great idea! Implemented with 79cc038.
