### ISSUE TITLE
Some Browsers Cause Server Failure

### ISSUE THREAD

**Issue by bakercp** [olab-io/ofSketch#25]
For an unknown reason, ipad editing fails after saving a new project.  When it redirects to the new saved project, it gets stuck on the `loading ...` screen.  This error leads to breaks in all of the other open browser windows as well.

**Comment by bakercp** [comment]
To reproduce:
1. Start server.
2. Open new project in desktop browsers, save and run.  Then close.
3. Open the editor window an ipad (or other ios device I suspect) using the ip address of the server machine.  Save a new project.  
4. It will then fail.

**Comment by bakercp** [comment]
On a related note, Safari and Firefox on desktop seem to exhibit similar behavior.  I believe there is something going on with the websocket -- but I'm not completely clear what the problem is yet.

**Comment by bakercp** [comment]
I haven't seen this happening lately ... @brannondorsey have you run into this?

**Comment by brannondorsey** [comment]
I haven't either, although I have not explicitly attempted the above steps to repeat the bug. I will look into this more soon.

**Comment by brannondorsey** [comment]
Confirmed to work on all major desktop browsers and iPhone + iPad Safari. Closing this issue for now.
