### ISSUE TITLE
More responsive toolbar when using narrow browsers

### ISSUE THREAD

**Issue by bakercp** [olab-io/ofSketch#28]
Currently the toolbar doesn't collapse in a Bootstrap friendly way when using narrow browsing windows.

e.g.

![ofsketch](https://cloud.githubusercontent.com/assets/300484/3196290/2aca002e-ed28-11e3-858b-1eb4d07fd6ed.png)

![ofsketch](https://cloud.githubusercontent.com/assets/300484/3196289/252e2cd0-ed28-11e3-915f-399a38a9ccd8.png)

This should be possible to fix with Bootstrap to make this more mobile friendly / responsive.

**Comment by brannondorsey** [comment]
Major toolbar buttons (run, save, open project, etc...) remain as standalones while website links, bug report, etc... are now stacked in a responsive menu. ofSketch version alert still needs to be styled correctly. Perhaps we could handle that with a modal (or would that be too annoying)?

**Comment by brannondorsey** [comment]
Version alert is now a "!" button that appears in the toolbar. Toolbar should now be fully responsive.
