### ISSUE TITLE
Editor: Implement Basic Autocomplete

### ISSUE THREAD

**Issue by bakercp** [olab-io/ofSketch#32]
Here is a simple example using an existing set of tags.

http://plnkr.co/edit/6MVntVmXYUbjR0DI82Cr?p=preview

**Comment by brannondorsey** [comment]
What tags do you see us using for the most basic of autocompletion? I was thinking for v0.0.2 we could use oF types?

**Comment by bakercp** [comment]
ofFunctions for now.  I'm trying to get it in there asap.  I just need to generate them.

**Comment by bakercp** [comment]
Basic auto-complete is implemented via ctrl+space.  I will be adding of functions to the index shortly.

We should also consider populating a collection of our own snippits.

**Comment by brannondorsey** [comment]
I have compiled an of function dictionary [here](https://github.com/olab-io/ofSketch/blob/develop/ofSketchApp%2Fbin%2Fdata%2FResources%2FofFunctionDictionary.json). I don't know what you are currently using, but this could be helpful. I can implement time-delayed autosuggest if you would like. Can you point me to where you are populating the autocomplete list right now?

**Comment by brannondorsey** [comment]
Basic autocomplete is now implemented. It is activated automatically with no keypress or lag (sublime text style). This will be improved later down the road.
