### ISSUE TITLE
Editor: Find / cmd-F styling is wrong / not working.

### ISSUE THREAD

**Issue by bakercp** [olab-io/ofSketch#40]
![ofsketch](https://cloud.githubusercontent.com/assets/300484/3212822/8111aa4a-ef76-11e3-8ce9-32c6aa020805.png)

**Comment by brannondorsey** [comment]
The Ace scrollbar is also the wrong color and many of the default keybindings don't work. I've got to figure out what is going on with our ace editor.

**Comment by brannondorsey** [comment]
After a huge headache + digging around at others examples online, I found that using ACE with bootstrap seems to do some weird default CSS clash stuff to ACE's search bar. I did some custom styling to try and offset it. Looks fine now, however if the user picks an outrageously large font-size some weird stuff might happen. I am closing for now but will further look into it if this continues to be a problem.
