### ISSUE TITLE
Editor: Configure settings

### ISSUE THREAD

**Issue by bakercp** [olab-io/ofSketch#42]
Would be nice to have this level of editor control:

http://ace.c9.io/build/kitchen-sink.html

**Comment by brannondorsey** [comment]
Just discovered (and implemented) ACE's default Settings Menu. It doesn't give full control, and there are some discrepancies with what you can change in the menu vs. what actually shows up in the editor but it gets us about 90% there. Currently defaults are not saved so each page refresh destroys changes. This needs to be played with.

![screen shot 2014-07-13 at 8 55 36 pm](https://cloud.githubusercontent.com/assets/3193533/3566562/06836cec-0afa-11e4-9f33-1b2bc9aa2d60.png)

**Comment by bakercp** [comment]
very nice.

**Comment by brannondorsey** [comment]
Very close to patching this up and allowing it to work with our `EditorSettings.json` to control global Editor Settings instead of the single Ace instance.

**Comment by brannondorsey** [comment]
A customized version of the ACE Settings Menu now writes to [`Resources/Settings/EditorSettings.json`](https://github.com/olab-io/ofSketch/blob/develop/ofSketchApp/bin/data/Resources/Settings/EditorSettings.json) and live updates all connected clients.
