### ISSUE TITLE
Gracefully Degrade if Port In Use (choose another port? print error?)

### ISSUE THREAD

**Issue by bakercp** [olab-io/ofSketch#47]
If the port is in use or the client can't connect to the server, the client should die more gracefully.  Currently it just says ... "loading", which is difficult to decipher.

**Comment by brannondorsey** [comment]
Perhaps we should also not use port 8998 seeing as it is the default port for ofxHTTP.

**Comment by bakercp** [comment]
Agreed.

**Comment by bakercp** [comment]
The default port has been changed to 7890 for now.  I'm modifying this bug report to be a bit clearer.

**Comment by brannondorsey** [comment]
I've added a blocking (and inescapable) modal for when the server connection is lost. Is it actually possible to handle a "port in use" error. If the port is in use we would not be able to send any data to the client to warn them. We could visualize an error like this in the ofSketch app somewhere.

**Comment by bakercp** [comment]
OK.  I was planning to do something about this on the server side -- that is, when the user tried to start a second server on the same port it would issue some sort of error or exception, but on OSX at least, this is still quietly running somehow ... so for the moment, I'm going to close this and move the issue of to ofxHTTP.
