### ISSUE TITLE
reference / forum / ofxAddons buttons not working on firefox

### ISSUE THREAD

**Issue by admsyn** [olab-io/ofSketch#59]
Firefox / OSX. Nothing seems to happen if I click them.

Works in Chrome and Safari though.

**Comment by bakercp** [comment]
Got any version info?

**Comment by admsyn** [comment]
Ah
- ofSketch v0.1.6
- Firefox 30.0
- OSX 10.9.3

**Comment by brannondorsey** [comment]
Fixed for next minor release. Thanks for pointing this out.
