### ISSUE TITLE
Add Version Update Checking on the Client

### ISSUE THREAD

**Issue by bakercp** [olab-io/ofSketch#6]
We can check for new releases w/ the API.

I'll have the server check this on the server side and then push an event to the client side, where you (@brannondorsey) can present the link to the user.

Requires that the server can report its current version information with a new method and requires that releases code includes release number.

e.g.
https://api.github.com/repos/brannondorsey/ofSketch/releases

**Comment by bakercp** [comment]
I got all of the back and front end working and moved.

@brannondorsey Can you clean up the "alert" so it is clickable and meshes well with the bootstrap style?

You can test your changes by just changing:

``` javascript
if (semver.gt(remoteVersion, localVersion))
{
///...
```

to 

``` javascript
if (semver.gt(remoteVersion, "0.0.0"))
{
```

**Comment by brannondorsey** [comment]
Great work @bakercp! Alerts are now bootstrapified as of https://github.com/olab-io/ofSketch/pull/35.
