### ISSUE TITLE
Class tabs must stack on smaller screens

### ISSUE THREAD

**Issue by brannondorsey** [olab-io/ofSketch#61]
Currently if you add enough classes the add class "+" button disappears and no more classes can be added. Classes that cannot fit on the screen should be represented by a dropdown menu.

**Comment by bakercp** [comment]
Also related, the tabs end up awkwardly underneath when the window is really narrow.

**Comment by brannondorsey** [comment]
With way that I am handling tabs right now with bootstrap, this kind of fix is fairly non-trivial. That said, it is a sizable issue and I am moving it up to v0.3.0.

**Comment by brannondorsey** [comment]
That was a sizable headache, but classes should now be stacking in a fairly pleasing way.
