### ISSUE TITLE
What is the current process for a version bump?

### ISSUE THREAD

**Issue by brannondorsey** [olab-io/ofSketch#62]
Do I simply bump the  [version `enum` in App.h](https://github.com/olab-io/ofSketch/blob/master/ofSketchApp/src/App.h#L121-L126)? It seems like there is also version info in the Xcode "general" app info. Is there anything else I need to do?

@bakercp, were you working on a script that publishes a release to github?

**Comment by bakercp** [comment]
Currently it's kind of manual ... I'm going to get it more fully automated soon.  I have some scripts that automatically update App.h, etc, but I want to make sure they work across platform or else they aren't much use.

**Comment by bakercp** [comment]
Resolved? @brannondorsey
