### ISSUE TITLE
Feedback form + send feedback button

### ISSUE THREAD

**Issue by brannondorsey** [olab-io/ofSketch#65]

**Comment by bakercp** [comment]
I'd like to figure out a way to make this pop up after a little while (and never pop up again after they take a survey) via cookies or on the server side.

Also, we need to think about how this is different from submitting bug reports (from the user's perspective).

**Comment by brannondorsey** [comment]
A pop up would be great, but I find those terribly annoying. I think it would be fine if we did the basic "not now", and "don't ask me again". I still vote that we have a button somewhere in settings (see below) that would allow people to send feedback at a designated time of their choice, or if they clicked "don't ask me again".

I see "Report a Bug" staying in the navbar until a stable release, and then getting moved to the settings dropdown with "About ofSketch" and "Send Feedback". What do you think?

![screen shot 2014-07-16 at 2 22 00 pm](https://cloud.githubusercontent.com/assets/3193533/3604282/94821ad6-0d1e-11e4-8455-71612430e006.png)

**Comment by bakercp** [comment]
Yeah, that looks great menu-wise, and yes, it's super annoying to be spammed for feedback.  That's kind of why I want a more experienced UI/UX person to jump in and help us think through an effective way to do user testing ...

**Comment by bakercp** [comment]
This is finished for now.  We're on to real-people testing.
