### ISSUE TITLE
Tracking User Habits for better design? Survey?

### ISSUE THREAD

**Issue by bakercp** [olab-io/ofSketch#66]
Is there an non-annoying and opt-in way gather data about how people are using the web interface?  Could this be done on an opt-in basis with Google Analytics or a similar tracking system?

Or would it be better to set a bunch of people up in a room and just watch them use it?

**Comment by bakercp** [comment]
Closing this for now.  Based on our experience at the hack-a-thon, I think the best way forward in the near term is to get together with people in person and learn by observation and self-reporting.

**Comment by brannondorsey** [comment]
Glad we didn't put the effort into something we only thought we might need ;)
