### ISSUE TITLE
Implement Server Side Settings

### ISSUE THREAD

**Issue by bakercp** [olab-io/ofSketch#7]
Not sure of the best way to implement settings on the server side. Here is an example of an EditorSettings.json file:

``` json
{
    "port": 9889,
    "hostname": "http://127.0.0.1",
    "icon": "some/path",
    "projectDir": "Projects",
    "sketchDir": "sketch",
    "addonsDir": "openFrameworks/addons",
    "projectExtension": ".sketch",
    "classExtension": ".sketch",
    "fontSize": 12,
    "tabSize": 4,
    "editorTheme": "ace/theme/twilight",
    "editorMode": "ace/mode/c_cpp",
    "editorHighlightActiveLine": false,
    "editorShowPrintMargin": false,
    "editorShowInvisibles": false,
    "editorAutopairCharacters": true,
    "keys": {
        "save": {
            "win": "Ctrl-s",
            "mac": "Command-s"
        },
        "run": {
            "win": "Ctrl-r",
            "mac": "Command-r"
        }
    }
}
```

On the backend, I have two ways that I could structure the class. The first is as follows:
## Option 1

``` cpp
class Settings {
public:
    Settings();
    bool save();
    bool load();
    const JSON::Value& getSettings();
    JSON::Value& getSettingsRef();

private:
    JSON::Value _data;
```

This class would easily be able to save and load settings files, and the data from those files would be accessible in code like this: 

``` cpp
int port = editorSettings.getSettings()["port"].asInt();
```
## Option 2

``` cpp
class EditorSettings {
public:
    Settings();
    bool save();
    bool load();

    int getPort();
    int getHost();
    // etc...

private:
    JSON::Value _data;
```

``` cpp
int port = editorSettings.getPort();
```
## Thoughts

Option one is nice because:
- It means that the Settings class doesn't have to be updated whenever the scheme of the EditorSettings.json file is changed. 
- The same Settings class can be used for both EditorSettings.json and ProjectSettings.json because it simply bundles load and save functionality as well as a few basic access methods.

Option two is nice because:
- It is more in line with openFrameworks/C++ standards.
- It keeps code outside of the EditorClass neat and straightforward.
- Less error prone.

Any suggestion? I'm leaning towards 2.

**Comment by brannondorsey** [comment]
Does option 2 make the most since for our style?

**Comment by brannondorsey** [comment]
Basic server side settings are now implemented. They are not, however, configurable on the front-end. They also need to be improved as not all of the ofSketch app is relying on the settings yet. This should be complete by https://github.com/olab-io/ofSketch/issues/19.
