### ISSUE TITLE
Name of sketch as tab title 

### ISSUE THREAD

**Issue by mileshiroo** [olab-io/ofSketch#72]
Hello Christopher and others,

I love ofSketch so far!

After using it for a few hours, I have a small suggestion. I think it would be useful if the title of tab in the browser matched the name of the sketch open in that tab. This way, one could visually distinguish between multiple open sketches. Currently, there is no way to do so: 

![screen shot 2014-07-17 at 10 43 17 pm](https://cloud.githubusercontent.com/assets/1015606/3622025/5cb3dc7c-0e25-11e4-8c4e-b0a4803df128.png)

Miles

**Comment by bakercp** [comment]
Smart!  Brannon, I'll let you take this one ... should just be setting the html title tag, no?

**Comment by bakercp** [comment]
Also, thanks @mlsptn.  Please keep the suggestions coming ... I'm super excited that you have used it for "a few hours"!  It makes all of this work worth it :)

**Comment by brannondorsey** [comment]
Hi @mlsptn! I will get on this and it will roll out in the next patch. Thanks for the issue, and glad you are using ofSketch!
