### ISSUE TITLE
Platform: armv7l (aka UDOO, BBB, pcDuino, Arduino Tre, etc).

### ISSUE THREAD

**Issue by mileshiroo** [olab-io/ofSketch#73]
Hello again,

Ali and I are trying to find a suitable version of oF to use on the UDOO board. 

I tried the linux 64-bit version of ofSketch on an UDOO running Ubuntu 12.04. When I launch the ofSketch executable, nothing happens (both launching 'Execute' or 'Execute in Terminal'). There are no error messages and nothing opens in the browser. I see that ofSketch also fails on rPi, might this be the same issue?

Would it help to compile ofSketch on the UDOO?

Miles

**Comment by bakercp** [comment]
Yes, if you can get it to compile on UDOO (aka armv7l) that would be great!  We can start distributing executables.  I'm working on armv6l (aka Raspberry Pi), I just haven't resolved a few issues yet.  Let me know if you get it compiled!

**Comment by bakercp** [comment]
I just got it working on RPi (https://github.com/olab-io/ofSketch/issues/58) and posted a recipe for compiling the UDOO (http://forum.openframeworks.cc/t/openframeworks-for-udoo-udoobuntu-working-recipe/16505).  

There are a few snags we need to work out, like passing the correct make flags to the compiler when compiling on the UDOO using ofSketch, but we should be able to add in that feature pretty easily.

**Comment by bakercp** [comment]
This is now working with UDOO, but it required a recompile of the Poco libs, etc.  We have to get a couple other issues worked out, but it's good news!

**Comment by bakercp** [comment]
I just added the makefile for UDOO to the oF core / master.  So this should be pretty easy now.

**Comment by bakercp** [comment]
Added.
