### ISSUE TITLE
Line Control

### ISSUE THREAD

**Issue by bakercp** [olab-io/ofSketch#77]
I've been researching ways to deal with better locating error messages without doing all sorts of sketchy math with line numbers etc.

I came across [this exciting preprocessor directive](https://gcc.gnu.org/onlinedocs/cpp/Line-Control.html)  `#line XXX` when I was digging into the Arduino build process this afternoon.

Basically, I believe that we should do it very similarly to the way they do.  Note how the following Arduino sketch gets transformed into a compile-ready file: 

``` c++
/*

This is an example of a bunch of comments.

*/

#include <SuperStepper.h>
#include <AFMotor.h>
#include <AFStepper.h>

AFStepper stepper0(48, 1);
AFStepper stepper1(48, 2);

void setup()
{  
  // Stuff
}

void loop()
{  
 // Even more stuff
}
```

Source that is actually shipped to the compiler:

``` c++
#line 1 "AFStepperExample.pde"






#include <SuperStepper.h>
#include <AFMotor.h>
#include <AFStepper.h>

#include "Arduino.h"
void setup();
void loop();
#line 11
AFStepper stepper0(48, 1);
AFStepper stepper1(48, 2);

bool goingUp0 = false;
bool goingUp1 = false;
int32_t target0 = 255;
int32_t target1 = 512;

void setup()
{  

}

void loop()
{  

}

```

These line directives are used to locate any compilation errors in the ORIGINAL sketch source, rather than the the processed source.

Implementing a filter that injects these line numbers before the includes are stripped will make it super easy to parse the error row / column back to the editor.

@brannondorsey Give the docs a read and let me know what you think ...

**Comment by bakercp** [comment]
Also, please let me know if you interpret its functionality the same way ... I may be off on how this works :)  Here's to wishful thinking!

**Comment by brannondorsey** [comment]
It works :)
