### ISSUE TITLE
When starting a new project in RPi, ACE editor missing styles.

### ISSUE THREAD

**Issue by bakercp** [olab-io/ofSketch#78]
I'm not sure why yet, but the Ace editor theme and styles are missing when used w/ Raspberry pi.

Basically this:

![christopher](https://cloud.githubusercontent.com/assets/300484/3716293/6d458d16-1608-11e4-9199-f1b5fb5d6f11.png)

**Comment by brannondorsey** [comment]
Does this occur on the current master branch?

**Comment by bakercp** [comment]
Just develop as far as I know.

**Comment by bakercp** [comment]
@brannondorsey I'll double check this on the 0.3.0 release and we can close it then if it's fixed.

**Comment by brannondorsey** [comment]
@bakercp, have you experienced this recently?

**Comment by bakercp** [comment]
Just tested.  No longer an issue ... it works amazingly well on Raspberry Pi!  Stop button is a life saver :)
