### ISSUE TITLE
Server fails if new project is opened in another tab while another project is compiling

### ISSUE THREAD

**Issue by brannondorsey** [olab-io/ofSketch#82]
If a project is opened while another project is compiling, the server fails with `signal SIGABRT` at 

```
ofNotifyEvent(events.onOpenEvent, eventArgs, this)
```

https://github.com/bakercp/ofxHTTP/blob/master/libs%2FofxHTTP%2Fsrc%2FWebSocketConnection.cpp#L92

**Comment by brannondorsey** [comment]
This also seems like a high priority for the GSoC release/ making ofSketch actually usable.

**Comment by bakercp** [comment]
Yes.

**Comment by bakercp** [comment]
So basically, this ofSketch does not like to open new projects when a compile task is running ...

**Comment by bakercp** [comment]
Any movement on this one @brannondorsey ?

**Comment by brannondorsey** [comment]
Not yet. I've been super swamped. Hoping to make some progress before the
weekend if I can. I have a feeling that it is coming from the backend
because the app crashes.

On Wed, Sep 24, 2014 at 12:32 AM, Christopher Baker <
notifications@github.com> wrote:

> Any movement on this one @brannondorsey https://github.com/brannondorsey
> ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/olab-io/ofSketch/issues/82#issuecomment-56626714.

## 

http://brannondorsey.com

**Comment by brannondorsey** [comment]
Fixed this for now by [commenting out](https://github.com/olab-io/ofSketch/blob/171b5583cc12c539df6f2ec9db775d9ddafb4554/ofSketchApp/src/App.cpp#L640-L650) a taskQueue frame that was being sent to the client from the server's `App::WebsocketOpen` event. We will need to look into this again if and when we implement a task manager.
