### ISSUE TITLE
Cross Platform Paths

### ISSUE THREAD

**Issue by bakercp** [olab-io/ofSketch#84]
Currently when creating paths, we use "/" as separators.  This is not the way of windows.  For cross platform support, we need to construct paths using `Poco::Path`, or avoid *nix style paths.

**Comment by brannondorsey** [comment]
How is this going? I realized that I was probably entirely unhelpful in my attempt. I'd be willing to tag team this tomorrow in oLab if that would be helpful.

**Comment by bakercp** [comment]
It's going.  Can you hop on chat?  I have some questions about this issue in particular.

**Comment by bakercp** [comment]
Solved for now.
