### ISSUE TITLE
GSOC Documentation

### ISSUE THREAD

**Issue by bakercp** [olab-io/ofSketch#86]
In order to make sure this project continues to generate interest and attract contributors, I think we should expand our current documentation into two documents.  The target audience for these documents will be developers who want to help continue to build ofSketch and those seeking to build features and addons that are ofSketch-"friendly".
- [x] Technical Document:  This document should expand upon the readme.md / architecture.md and proposal and include a clear explanation of the architecture of ofSketch.  The goal of this document is to bring potential developers up to speed with the technical aspects of ofSketch.  Topics might include:
  - [x] The relationship between the client / server.
  - [x] The communication protocols between the two.
  - [ ] Task management.
  - [x] Compilation (how do we do it?) 
  - [x] Clear documentation of the simplified "sketch" format. 
  - [ ] What is the best way to contribute?
- [x] Roadmap:  Where do we go from here?  What do we need help with?  
- [ ] Updated < 2 minute getting started video.
- [ ] Create community "help wanted" issue.
  - [ ] Need help with language translations, etc.

**Comment by brannondorsey** [comment]
All of this sounds really great! What do you see the main function of the micro website being? Eventually will ofSketch v1.0 be included on the openFrameworks website, and until then we have a designated ofSketch website to download + host info about the project?

**Comment by bakercp** [comment]
I think the idea of a micro website would be a simpler, friendlier landing place kind of like http://hello.processing.org/.  But that is probably outside the scope of the docs.  Feel free to remove it from this checklist.

**Comment by brannondorsey** [comment]
Via a GSoC Email blast:

> This is a reminder that the soft "pencils down" date is coming up on Monday, 11 August. We recommend that your code be complete by then and that you spend the last week of the program doing any documentation or wrap-up that your project needs.

I am going to start making these docs more of a priority as the week progresses. @bakercp, will you be downtown any time in the next few weeks to discuss some of these topics in person? If not I can also meet at a coffee shop.

**Comment by bakercp** [comment]
I'll be in the olab after noon tomorrow.

**Comment by brannondorsey** [comment]
I was thinking about creating a ROADMAP.md file to go with the rest of our "ALLCAPSMDFILES.md"s. I think it has the highest chance to be read + paid attention to if we bundle it. I was also thinking of doing a sizable revamp to ARCHITECTURE.md, including that architecture image I shared with you, as well as the info specified in the "Technical Document" mentioned above. What do you think? Does that seem like the best place for that stuff?

That brings our .md list to:
- README.md
- LICENSE.md
- CHANGELOG.md
- CONTRIBUTING.md
- BUILDING.md
- ARCHITECTURE.md
- ROADMAP.md

This seems like a good list (in my opinion), but might be a bit overwhelming/confusing for the normal user. Perhaps our build script could remove all but README.md and LICENSE.md, and the rest could be included in our repo.

Anyway, does the combination of the above (linking back and forth to each other of course where applicable) feel like the appropriate outlet for our documentation needs specified in the original issue post up top (plus of course a new video)?

I think ofSketch could do well with its own website down the road (unless we want to include it on the oF website), but will these satisfy our GSoC documentation needs?
