### ISSUE TITLE
Compiling ofxJSON on Linux

### ISSUE THREAD

**Issue by underdoeg** [olab-io/ofSketch#89]
This is actually a bug/question in ofxJSON but since the addon is forked and doesn't have a bugtracker. I'll post it here.

Currently I can't compile ofSketch because I don't have jsoncpp installed and this line askes for it: https://github.com/bakercp/ofxJSON/blob/master/addon_config.mk#L11

I think this is because the version of jsoncpp shipped with the addon used to not compile on linux. (or at least not on my system) But now the one installed was too old but the included with ofxJSON is compiling fine.

**Comment by bakercp** [comment]
Hey @underdoeg - what version of Linux are you using?  Theoretically, ofxJSON should completely ignore the jsoncpp sources in the `ofxJSON/libs/jsoncpp` folder and should run from the system libraries (e.g. those installed via something like `sudo apt-get install libjsoncpp-dev`).  It [looks like the jsoncpp](https://github.com/open-source-parsers/jsoncpp) sources are getting some attention these days -- so perhaps the newer versions will be compatible with the addon?

**Comment by bakercp** [comment]
Ahh ... I just re-read your question and I think I misunderstood.  Let me know what version of Linux you're using so we can add a note to the documentation.  In the mean-time, you can probably just modify the addons_config.mk file to meet your needs.  Perhaps if we update to the newer versions of jsoncpp, the source-based compile will be compatible from source across the board on linux ... ?

**Comment by underdoeg** [comment]
I'm on arch linux with up to date packages. Jep, I used to ignore the shipped jsoncpp and used the one provided by my system. But then I got an error 

`error: ‘ArrayIndex’ is not a member of ‘Json’` 

I guess ArrayIndex is a new feature and not part of the "official" release yet. 

You could also just use unsigned int for now? 

https://github.com/brannondorsey/ofSketch/blob/develop/ofSketchApp/src/Project.cpp#L289

**Comment by bakercp** [comment]
Ahh, yeah I just added that.  It should probably be unsigned.  It was a temporary attempt to start getting rid of all of the unsigned / signed integer comparison warnings ... do you know which version of jsoncpp is installed on your system?

**Comment by underdoeg** [comment]
Yes, I think you can safely replace it with an unsigned int.
https://github.com/open-source-parsers/jsoncpp/blob/8050d8b677a5a9b9ccbc3b19ecedbbd7f34e083e/include/json/forwards.h#L26

same here

https://github.com/brannondorsey/ofSketch/blob/develop/ofSketchApp/src/Compiler.cpp#L80

The jsoncpp version is  0.5.0
https://www.archlinux.org/packages/extra/x86_64/jsoncpp/

**Comment by underdoeg** [comment]
Btw the ofxJSON examples still work, so it really is just that Json::ArrayIndex type

**Comment by bakercp** [comment]
I just added a commit to fix it -- can you give it a try?  I think it was just in that once place ...

**Comment by bakercp** [comment]
also note that these updates are pushed to the main olab-io repo (I think some of your links were to @brannondorsey's repo).

**Comment by underdoeg** [comment]
ok thanks. That fix works but looks like this is also an issue:

```
../../../addons/ofxJSON/src/ofxJSONElement.cpp: In member function ‘bool ofxJSONElement::openLocal(const string&)’:
```

This is something within ofxJSON. Looks like my previous & successful compile of the ofxJSON/example-file project read from the cache.

**Comment by underdoeg** [comment]
Somehow I feel this thing might get out of hands quickly. Do you have any idea why the shipped jsoncpp files don't compile on linux?

**Comment by bakercp** [comment]
I don't ... I feel like it might have been some header conflict or something.  I'd prefer to use this all from source, so I'll take a look at it now.  Perhaps the latest jsoncpp source will work on linux now.

**Comment by underdoeg** [comment]
I just tried it. Doesn't look too good. Stuff like

```
/usr/include/stdio.h:826:23: error: variable or field ‘clearerr’ declared void
 extern void clearerr (FILE *__stream) __THROW;
                       ^
/usr/include/stdio.h:826:23: error: ‘FILE’ was not declared in this scope
/usr/include/stdio.h:826:29: error: ‘__stream’ was not declared in this scope
 extern void clearerr (FILE *__stream) __THROW;
                             ^
/usr/include/stdio.h:828:18: error: ‘FILE’ was not declared in this scope
 extern int feof (FILE *__stream) __THROW __wur;
                  ^
/usr/include/stdio.h:828:24: error: ‘__stream’ was not declared in this scope
 extern int feof (FILE *__stream) __THROW __wur;
                        ^
/usr/include/stdio.h:830:20: error: ‘FILE’ was not declared in this scope
 extern int ferror (FILE *__stream) __THROW __wur;
                    ^
/usr/include/stdio.h:830:26: error: ‘__stream’ was not declared in this scope
 extern int ferror (FILE *__stream) __THROW __wur;
```

Looks like some sort of include order, namespace, hard to solve conflict...

**Comment by underdoeg** [comment]
That is just pasting the source from https://github.com/open-source-parsers/jsoncpp/tree/master/src/lib_json and not building it via cmake...

**Comment by bakercp** [comment]
Can you try this branch?

https://github.com/bakercp/ofxJSON/tree/develop

---

http://christopherbaker.net

**Comment by underdoeg** [comment]
That one is complaining about 

```
../../../addons/ofxJSON/libs/jsoncpp/src/json_reader.cpp:7:26: fatal error: json/reader.h: No such file or directory
 # include <json/reader.h>                       ^
```

**Comment by bakercp** [comment]
Yeah, I think I just fixed that -- try pulling again.

**Comment by underdoeg** [comment]
yessir! Looks like that did it. Now the example-file compiles and so does the latest ofSketch. Out of curiosity: What did you do?

**Comment by bakercp** [comment]
I have successfully the develop branch ofxJSON examples from the new shipped source on linux and linux64 (ubuntu 12 / 14).  I'm compiling now on the armv6l (RPI)/armv7l(Udoo), so I should know if that worked in a few days ;)

**Comment by underdoeg** [comment]
Great. Also good to hear that I am not the only one without cross compiling set up ;)

**Comment by bakercp** [comment]
The fix was:
- `git clone https://github.com/open-source-parsers/jsoncpp.git` latest version of jsoncpp.
- `cd jsoncpp`
- `python amalgamate.py` // produces a smaller set of files (see jsoncpp README.md)
- copy the amalgamated files from `jsoncpp/dist` into the libs folder of ofxJSON
- Removed all lines from `addon_config.mk` that instruct the makefile system to use system libs ...

**Comment by bakercp** [comment]
I'm also testing on win_cb and vs2012 now just to make sure, but if those all pass, I'll push ofxJSON develop to master.

**Comment by underdoeg** [comment]
Ah right. Awesome. Now that makes a lot of sense. I guess the important part was

...
The amalgamated sources are generated by concatenating JsonCpp source in the correct order and **defining the macro JSON_IS_AMALGAMATION to prevent inclusion of other headers**.
...

**Comment by bakercp** [comment]
I'm going to leave this open for the moment to remind me to test all of those other platforms and then merge develop to master.  Thanks for the report!

**Comment by underdoeg** [comment]
thanks for the quick fix

**Comment by bakercp** [comment]
ofxJSON just got a big facelift and all has been tested across many platforms and merged into master.  @underdoeg could you give my master branch a check when you get a chance?  I also sent a PR to @jefftimesten with all of the updates so hopefully it will make it upstream for all the linux people.

**Comment by underdoeg** [comment]
Looks good. I was able to compile to ofxJSON examples and the ofSketch develop branch.
