### ISSUE TITLE
ofSketch Settings

### ISSUE THREAD

**Issue by brannondorsey** [olab-io/ofSketch#94]
Global ofSketch settings to configure:
- [x] Port
- [x] Buffer Size
- [x] Projects directory
- [x] openFrameworks directory
  etc...

Right now whenever you download a new ofSketch version all of your projects are gone, and must be manually moved to the new version's project folder. This issue can be alleviated by allowing users to specify a "Projects" directory.

**Comment by bakercp** [comment]
There are probably some cross-platform application settings tools in Poco http://pocoproject.org/slides/180-Configuration.pdf

Theoretically, these settings would be saved in the user's "/User/username/library/Preferences" folder on a mac and in a similar location on other platforms.

Alternatively, we could just create a hidden .ofSketch prefs file in the user's home directory. 

Access to user and other environemntal information is available via Poco 

http://pocoproject.org/slides/050-PlatformAndEnvironment.pdf
http://pocoproject.org/docs/Poco.Environment.html

CB

**Comment by bakercp** [comment]
e.g.

```
#include "Poco/Environment.h"
/// ...
    if (Poco::Environment::has("HOME"))
        std::cout << "Home: " << Poco::Environment::get("HOME") << std::endl;
```

returns `/users/myusername`.

**Comment by brannondorsey** [comment]
We can do that, for now I was planning on using our `Resources/Settings/OfSketchSettings.json` just like what we do with `EditorSettings.json`, and them having them configurable from the "ofSketch Settings" modal.

How do you feel if we dynamically updating each project's `config.make` with an absolute path to whatever they specify as their openFrameworks directory, that way their `Projects` folder can live anywhere on their machine (for instance, in `Home/Documents` like Arduino does it).

**Comment by bakercp** [comment]
I'd prefer not to modify config.make -- instead we can set an environmental variable as a process arg for OF_ROOT when we compile.  That way the user's project directory can live anywhere.

Settings that are bundled with the app bundle don't transfer to new versions very easily, which is why I suggested the Home idea.  That way users could keep their settings on upgrade and also have multiple project folders that they could configure and save to their non-bundled user settings.

**Comment by brannondorsey** [comment]
Ah, makes since! Lets do that :)

**Comment by brannondorsey** [comment]
Long term, are we interested in moving in the direction of encouraging one ofSketch Projects folder? If so, the next ofSketch release will cause a bit of a problem, as it will define the first "global" projects folder. From then on, that first folder will be the default, with each new release will allow a user you to change their default projects folder. This could lead to some confusion if it is not made explicitly clear that this has happened. For instance, if they do not move the ofSketch v0.4.0 `Projects/` folder to a notable place, and `.ofsketchsettings` has registered that folder to be the global ofSketch `Projects/` folder, then their v0.5.0 download will write to the folder bundled in v0.4.0. While this functionality is preferred, I suggest that we come up with a nice way to make the transition. Some options are:
- Move `Projects` outside of `data/Projects` for v0.4.0 and draw attention to the fact that this folder, unless changed in ofSketch settings, will now be the default Projects folder.
- Install an `ofSketch/` folder in Documents (like Arduino), with a `Projects` folder.

I am leaning towards the second, as it clearly sets a new standard for managing ofSketch workflow. It also allows us to easily extend the `Documents/ofSketch` folder to include Examples, Addons, and even oF distros to keep everything in one place. @bakercp, what do you think?

**Comment by bakercp** [comment]
I would take our cue from processing / arduino.  Examples and core libraries are bundled with the app in the applications folder.

User sketches and addons (aka libraries in P5/arduino speak) go in the sketches folder.

That said, I think we should hold off on moving libraries just yet -- I'd like to see those stored in (potentially) a third non-bundle location, but managed (eventually) but the ofSketch gui.

**Comment by brannondorsey** [comment]
> That said, I think we should hold off on moving libraries just yet -- I'd like to see those stored in (potentially) a third non-bundle location, but managed (eventually) but the ofSketch gui.

So are you saying move only Projects (and maybe non-core addons) to a `Documents/ofSketch` like location for now or wait?

 I can't really implement any kind of "ofSketch Settings" that allow you to specify an oF distro + Projects folder until they exist somewhere outside of the ofSketch bundle without causing user headaches. 

That said, I think we are at a stage where we can make a change like that. Especially before the GSoC deadline. We just need to be careful that the standard that we adopt is what we can see ourselves staying with.

**Comment by bakercp** [comment]
I think for 0.4.0 I'd like to see:
- Move ofSketch application settings outside of the bundle to a sensible location.  I'd vote for the .ofSketchSettings.json hidden file in the user's home directory for now.  This should have all of the user's application settings in it.
- Move User's projects folder outside of the data bundle.  User-specified settings to locate it.
- Keep Examples inside the bundles in an examples folder.  These, like Arduino / Processing, should be read only, but the user can save them to their own Projects folder if they want to modify them.
- Keep addons (core and other) in the bundle and manage them via the gui (advanced users can hack and manually add if they like).
- Keep openFrameworks root in the bundle - "aka built-in".

In the future 0.5.0?  These are kind of starting to border on ... "you should graduate to a big IDE now territory ..."
- Allow users to specify an addons folder that is outside the bundle.
- Allow users to specify an openFrameworks root that is outside of the bundle (or set it back to "built in").

**Comment by brannondorsey** [comment]
Agreed all across the board!

**Comment by brannondorsey** [comment]
The ofSketch Settings modal is now writing to and loading from `$HOME/.ofsketchsettings.json`.

> I'd prefer not to modify config.make -- instead we can set an environmental variable as a process arg for OF_ROOT when we compile. That way the user's project directory can live anywhere.

What is the process for setting the OF_ROOT via our `MakeTask` class? I'm currently setting `MakeTask::Settings.ofRoot` to the correct openFrameworks directory, but it isn't being `push_back`ed as an argument and I am not familiar enough with Make to know how to specify this.

**Comment by bakercp** [comment]
you should be able to set OF_ROOT like this in MakeTask.cpp

```
    if (!_settings.ofRoot.empty())
    {
        _args.push_back("OF_ROOT=" + _settings.ofRoot);
    }

```

OF_ROOT should be the relative location from the project folder (or absolute path if required).  OF_ROOT is set to ../../.. by the makefiles by default IFF OF_ROOT has not been defined in config.make OR as a command line argument (which we are doing in this case).    To experiment with it, you might take one of your existing projects, place it somewhere random on your computer and then compile it manually with `make OF_ROOT=xxxxxxxx` from the project directory.

**Comment by brannondorsey** [comment]
This works well! The Projects + openFrameworks directories can now be specified in ofSketch Settings.

**Comment by bakercp** [comment]
:+1:

**Comment by bakercp** [comment]
So, can we close this @brannondorsey

**Comment by brannondorsey** [comment]
Closing for now. Any additional features/settings can be opened as separate issues.
