### ISSUE TITLE
loadImage fails when compiling with ofSketch-develop

### ISSUE THREAD

**Issue by brannondorsey** [olab-io/ofSketch#95]
For some odd reason I get a Signal SIGABRT runtime error on App.cpp line: 67 when compiling ofSketch with ofSketch-develop branch of openFrameworks: https://github.com/bakercp/openFrameworks/tree/ofSketch-develop

``` cpp
_logo.loadImage("media/openFrameworks.png");
```

I can confirm that I have `openFrameworks.png` in my `data/media` folder and I get now "Image not found" error. This is all that prints to the console before hanging the app: 

```
libc++abi.dylib: terminating with uncaught exception of type char const*
```

**Comment by bakercp** [comment]
I've seen that error before -- it started happening with the Poco upgrade -- 

See my report here:

https://github.com/openframeworks/openFrameworks/pull/3116

The workaround for the moment is to not load the image :)

I believe it has something to do with the freeimage library needing to be updated, but I'm not sure yet.

**Comment by bakercp** [comment]
Note to self: http://stackoverflow.com/questions/12542971/using-libstdc-compiled-libraries-with-clang-stdlib-libc

**Comment by bakercp** [comment]
Closing this for now, as it will be resolved in the oF master branch.
