### ISSUE TITLE
Add Setting to disallow web connections from clients that are not on the localhost.

### ISSUE THREAD

**Issue by bakercp** [olab-io/ofSketch#96]
Disable remote web connections by default.  Enable via whitelist, etc.

**Comment by brannondorsey** [comment]
I've just added `allowRemote` and `whitelistedIPs` (array) to the ofSketch Settings GUI. They are currently being saved to and loaded from the `OfSketchSettings` object on the backend. They can be queried via `OfSketchSettings::getAllowRemote()` and `OfSketchSettings::getWhitelistedIPs()`.

I'm not sure of the best way to handle which IPs get responses from the server on the backend, or what those responses should be (forbidden if not whitelisted?). @bakercp, with your knowledge of ofxHTTP do you want to actually implement this on the backend? Alternatively, you could point me in the right direction :smiley:.

**Comment by bakercp** [comment]
Cool.  I'll implement.  Just got a few other things in the queue before I do it.

**Comment by bakercp** [comment]
Fixed with b901d47ac34c00a8f93cfdc631400672a26ea4a7
