### ISSUE TITLE
Heavy testing for GSoC release

### ISSUE THREAD

**Issue by brannondorsey** [olab-io/ofSketch#97]
All GSoC related coding must stop on August, 18th 19:00 UTC. I will obviously keep working on the project, however the zip that I upload to Google can't contain any code from after that date. I propose setting aside a substantial amount of time to testing all currently implemented features on all platforms, on the 15th or 16th to give enough time to fix what we may find.

**Comment by bakercp** [comment]
Sounds good to me.
