### ISSUE TITLE
not running in OSX 10.8.5

### ISSUE THREAD

**Issue by nbriz** [olab-io/ofSketch#99]
like @bakercp said:
The web interface, etc seemed to work -- but the connection to the server seemed broken 
#### User Info
- ofSketch 0.3.0
- Target: OSX
- User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36

**Comment by brannondorsey** [comment]
Thanks @nbriz, I am going to move this to https://github.com/olab-io/ofSketch/issues/98 and see if we can get it worked out.
